### ISSUE TITLE
Question: metagenomes or MAGs?

### ISSUE THREAD

**Issue by Ahmed-Shibl** [AlexanderLabWHOI/EUKulele#30]
Hi EUKulele developers, thanks for this tool - I'm excited to start using it soon.

Can I run my metagenomic dataset right away or do I first have to generate MAGs? I have metagenomes with coral and symbiodinium reads but unfortunately was not able to generate MAGs with Metabat or Maxbin.

Thanks,

**Comment by akrinos** [comment]
Hi Ahmed,

EUKulele is designed to run on MAGs (and that's the recommended use), but without having generated them, if you have a metagenome assembly, you would technically still be able to run EUKulele on the contigs, more suitably using the metatranscriptome option (since that does not assign a consensus annotation to the metatranscriptome, as is the goal to do with MAGs), just with caveats, as you would be assuming that each assembled contig could be presumed to have come exclusively from a single organism despite the failure of Metabat/Maxbin.

Thanks so much for your interest!

Arianna
