### ISSUE TITLE
Missing taxonomy_counts/test_all_division_counts.csv

### ISSUE THREAD

**Issue by michoug** [AlexanderLabWHOI/EUKulele#36]
Hi,
I seem to be missing the file` test_all_division_counts.csv` when running version 1.0.4 
`EUKulele -m mags -s temp/ -o test --CPUs 3 --database mmetsp`

Here is the error I found in the file `busco_query_metabat.4.log`

`Not all files needed to run BUSCO query  (output of BUSCO run) found; check log file for details. Here is the error: [Errno 2] No such file or directory: 'test/taxonomy_counts/test_all_division_counts.csv`

**Comment by akrinos** [comment]
Hi @michoug ! It looks like the previous taxonomy visualization step has failed at some point. Would you mind checking if anything is printed in `log/tax_vis.err` or `log/tax_vis.out`? Also, could you check what is in the `test/taxonomy_counts` folder as printed in the error message above? Thanks!

**Comment by michoug** [comment]
Hi,
In the `test/taxonomy_counts`, there is 

```
test_all_class_counts.csv
test_all_family_counts.csv
test_all_genus_counts.csv
test_all_order_counts.csv
test_all_species_counts.csv 
test_all_supergroup_counts.csv
```
the `log/tax_vis.err` is empty while in the `log/tax_vis.out`, there is written this

```
['supergroup', 'class', 'order', 'family', 'genus', 'species']
supergroup
0
['supergroup', 'class', 'order', 'family', 'genus', 'species']
class
1
['supergroup', 'class', 'order', 'family', 'genus', 'species']
order
2
['supergroup', 'class', 'order', 'family', 'genus', 'species']
family
3
['supergroup', 'class', 'order', 'family', 'genus', 'species']
genus
4
['supergroup', 'class', 'order', 'family', 'genus', 'species']
species
5
```

**Comment by akrinos** [comment]
Hi @michoug, how did you install `EUKulele`? This may be a versioning issue. Thanks for your patience!

**Comment by michoug** [comment]
Hi, I installed it with pip, version 1.0.4

**Comment by akrinos** [comment]
Hello @michoug - I think you might have found something that was not properly updated in v1.0.4 after we changed the level hierarchy! Apologies that this happened, but excited to have found it, since that means that everything up to this point worked properly + you are using a database which triggers the error, whereas I was testing the new database. Essentially, recently I changed the reference database setup, making the taxonomic levels that could be assigned a bit more flexible in the process. Downstream in the BUSCO steps, the previous hierarchy managed to stick around in one spot. 

I have fixed the code accordingly and am testing the change now - I will let you know when the adjustment is ready to download via pip. From there, you should hopefully be able to update the download and pick up where you left off. 

Thanks so much for using the software!

**Comment by akrinos** [comment]
Apologies for the delay on this @michoug ! Could you try out v1.0.5? pypi.org/project/EUKulele/1.0.5/

**Comment by michoug** [comment]
Thanks a lot, it worked !!
