### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by susheelbhanu** [AlexanderLabWHOI/EUKulele#54]
Hi all, 

I'm running `eukulele` using the latest version available on conda and getting the following error:
```bash
usage: eukulele [subroutine] --mets_or_mags [dataset_type] --sample_dir [sample_directory] --reference_dir [reference_database_location] [all other options]
EUKulele: error: argument subroutine: invalid choice: '/hdd0/susbus/results/eukulele_input' (choose from '', 'all', 'download', 'setup', 'alignment', 'busco', 'coregenes')
Running EUKulele with command line arguments, as no valid configuration file was provided.
```

The current documentation **does not** reflect the need to input the `subroutine` flag. Could you please update this when possible?

Thank you!

**Comment by akrinos** [comment]
Hello @susheelbhanu ! What's going on here is that it appears that you have added the input directory and the program is not recognizing that it's a flag argument - could you paste the full command you're using? The error suggests that the path is being interpreted as a subroutine not because a subroutine was required but rather because no flag was included before this argument (so it figures you intended it to be a subroutine).

**Comment by susheelbhanu** [comment]
@akrinos thanks for the quick response. The error seems to be fixed now, but just for legacy sake, here is how I have it setup:
```EUKulele all -m mets --sample_dir {input} --out_dir {output[0]} --database {params.db} --scratch {params.scratch} --CPUs {threads} --alignment_choice {params.aligner} --reference_dir {params.ref_dir} ```

Thank again!
